- _changes.html
- dev/_head.html
- dev/_security.html
- docs/_contribute.html
- docs/_index.html
- docs/_programs.html
- docs/_projdocs.html
- docs/_tooldocs.html
- libcurl/_competitors.html
- libcurl/lua/_index.html
Encountered a broken about URL earlier today and decided to look for others. The first commit fixes encoding issues which upset the Python parser, the second one fixes some dead links.
Excluded from the scans are:
'_press.html', # External links
'_newslog.html',
'_changes.html',
'_oldnews.html',
'_oldnews2.html',
Those contained many dead (internal) links, those were skipped for now since they are very old.
> Fix dead links

- libcurl/nodejs/_index.html
The text is mostly based on the one used by the python binding at https://github.com/curl/curl-www/blob/master/libcurl/python/_index.html
> Update Node.js binding page with more detailed info

- rfc/filedesc
[RFC2388](https://tools.ietf.org/html/rfc2388) is obsolete. [RFC7578](https://tools.ietf.org/html/rfc7578) was published in July 2015.
> Updated RFC 2388 to RFC 7578

- dev/explainopts.t
- dev/summarize.pl
- docs/_ssl-compared.html
See the individual commitmessages for more information, but the gist is:
* Removes AxTLS and QSOSSL from the comparison
* Removes AxTLS from the autobuilds
* Adds MesaLink to the autobuilds
> Random TLS refresh

- latest.pl
> latest.pl: moved mirror from manitu.de to netcup.de

- dev/dev.js
While the current coding is legal Javascript, relying on the automatic semicolon insertion can hide subtleties. Also, fixing these two small things will give us a clean bill of health on LGTM as a bonus.
> dev: Terminate all lines with semicolon

- windows/mkfiles.pl
Starting with 7.73.0_3, curl-for-win started adding a GPG signature for each .zip and .tar.gz files with a .asc suffix, so let's make sure that these are not caught by the regexp.
Ref: https://github.com/curl/curl-for-win/issues/15
> windows: try fixing zip sizes intermittently appearing as zero

- curl.css
- dev/summarize.pl
- docs/_comparison-table.html
- docs/_libs.html
When curl 7.78.0 ships without metalink support, it's time to clean
out any references to curl supporting metalink. This will scrub the
autobuild feature identifier even for older builds which did enable
metalink, but it seems a pretty low price to pay for simplifying.
> metalink: remove mentions of metalink

- windows/_index.html
- windows/mkfiles.pl
The new packages contain all, previously separately packaged files in two, per-target (win64 & win32), files. So, replace the hardcoded list of dependencies along with their download URLs, with a dynamically generated list with names and version numbers only, similar to the tool dependency section was already. This will also adapt to any configuration changes done in curl-for-win builds, e.g. it will show openssl-quic and list nghttp3 + ngtcp2 if/when those builds are made default.
> windows: update dl page for curl-uni, the new unified packages

- windows/_index.html
- windows/unpack.pl
Ref: https://github.com/curl/curl-for-win/commit/0528a0cffcb1c4180304abfcf35994181997dce5
I changed '64 bit' to 'x64' and '32 bit' to 'x86' on the page to use
Windows-terminology an to differenciate from the new arm build.
win64/win32/win64a in the filenames remain a little bit ambiguous so
it's an option to rename them, though it will break existing URLs:
`-win64` → `-win-x64`
`-win32` → `-win-x86`
`-win64a` → `-win-a64` or `-win-arm64`
> windows: add support for ARM64 builds

- ca/listpem.pl
- ca/update.sh
The unversioned https://curl.se/ca/cacert.pem has a checksum file at https://curl.se/ca/cacert.pem.sha256.
This patch adds a checksum file for the versioned counterparts: https://curl.se/ca/cacert-2022-12-31.pem.sha256 for https://curl.se/ca/cacert-2022-12-31.pem
This allows to verify the expected checksum for versioned cacerts.
Caveat: This patch doesn't add the checksum files retroactively, the current latest release included. Only the next release will have an .sha256 file.
> ca: create .sha256 checksum file for versioned downloads

- ca/update.sh
This logic can/should be deleted after letting it run once.
> ca: generate missing .sha256 files retroactively

- _download.html
I had made previous branch assuming we would get curl/curl on docker ... now not going to pursue that anymore so switching invoke to pull from docker to reflect that
> fix docker pull pull/download invoke

- docs/listvulns.pl
And not just a colored circle, for improved accessibility
Reported-by: MaeIsBad on github
Fixes #253
It makes the list look like this:
> docs/listvulns: show vulnerability severity with a circled letter

- _index.html
- curl.css
- docs/comparison.css
- libcurl/c/_example-templ.html
- libcurl/c/_example-warn.html
This PR fixes some contrast / styling issues that happen when browsing with dark mode preference.
Here are before/after screenshots of the main fixes:
**Home page sidebar boxes**
<details><summary>Before</summary>
</details>
<details><summary>After</summary>
</details>
**Table Rows**
<details><summary>Before</summary>
</details>
<details><summary>After</summary>
</details>
**Comparison Tables**
<details><summary>Before</summary>
</details>
<details><summary>After</summary>
</details>
**Code examples - Related boxes**
<details><summary>Before</summary>
</details>
<details><summary>After</summary>
</details>
**Code examples - Warning boxes**
<details><summary>Before</summary>
</details>
<details><summary>After</summary>
</details>
> Fix various dark mode contrast issues

- _index.html
- curl.css
Tweak ee10e76946fcfe55cabbe4f0b4b6858be7f0537f to reduce border contrast in sponsor boxes and restore the non-contrasty borders on the download page, while adding a separator line to make the OS headers stand out:
---
Before:
After:
---
Before:
After:
> dark mode: sidebar-box and downloads border tweaks

- docs/CVE-2023-32001.md
This PR fixes typos and does some minor rewords for comprehension in CVE-2023-32001.md.
> Fix typos and reword in CVE-2023-32001.md

- docs/_ssl-compared.html
openssl can do native cert from curl 8.3.0.
gnutls can do native cert from curl 8.5.0.
> [update] openssl Native cert check as GnuTLS.

- windows/mkfiles.pl
Change each dependency + version line into a link to the original source (or package) that we used for the build.
Also include curl sources in the list. This isn't stricly necessary, but otherwise curl would be the only component without a direct link to its source code.
Caveat: Needs an `fcpp` update bumping up `NBUFF` and `NWORK` to make it process the longer `DEP_TOOLS` (356 bytes) and `DEP_PKGS` (1013 bytes) macros.
https://github.com/bagder/fcpp:
```diff
diff --git a/cppdef.h b/cppdef.h
index c188a22..c5b44b5 100644
--- a/cppdef.h
+++ b/cppdef.h
@@ -299,11 +299,11 @@
#endif
#ifndef NBUFF
-#define NBUFF			512
+#define NBUFF			2048
#endif
#ifndef NWORK
-#define NWORK			512
+#define NWORK			2048
#endif
#ifndef NEXP
```
Or, build it with `CPPFLAGS='-DNBUFF=2048 -DNWORK=2048'` for …
> windows: add links to dependencies

- windows/_index.html
Prepare the download page for releases without 32-bit binaries.
Refs:
https://github.com/curl/curl-for-win/commit/08a2dad52e28f39123c15d55708079a4edf243f7
https://github.com/curl/curl-for-win/discussions/68#discussioncomment-8982982
> windows: make 32-bit download optional

- dev/_howto.html
- dev/_missing.html
- dl/mktable.pl
- libcurl/_features.html
- libcurl/_index.html
Also fixup `Win32`/`Win64` to appear as `Windows 32-bit`/`64-bit` on
the download page sidebar.
> tidy-up: Mac OS X -> macOS

- _menu.html
Mainly to declutter it and make it easier to find the options a user is more likely to want to find directly from this page.
The other options remain accessible from the docs menu in the libcurl section.
> menu: remove a few libcurl options from the front page menu

- docs/Makefile
curl/curl-www#187 version 2 :D
This is achieved by generating thanks.gen as
user1
&middot;
user2
&middot;
user3
Instead of as
user1&nbsp;&middot;
user2&nbsp;&middot;
user3&nbsp;&middot;
`&nbsp;` would add an unwanted extra (non-breaking) space, so I just removed it.
> thanks.gen: don't add an extra &middot; at the end

- windows/Makefile
- windows/_microsoft.html
- windows/term.css
- windows/term.t
To make them easier to read.
Makes it look like this:
> windows/microsoft: add padding to the "terminal lines"

- windows/_index.html
- windows/mkfiles.pl
It will be picked up from the next curl-for-win release.
Ref: https://github.com/curl/curl-for-win/commit/053daa195f2656cf297c7972a345ea16ef4cb1a1
---
> windows: show -V output

- .github/workflows/badwords.yml
- .github/workflows/make.yml
- .github/workflows/perlcheck.yml
- .github/workflows/spellcheck.yml
Fixes deprecation warnings.
`The following actions uses node12 which is deprecated and will be forced to run on node16: actions/checkout@v2.`
`The following actions use a deprecated Node.js version and will be forced to run on node20: actions/checkout@v2.`
> ci: bump actions/checkout to v4

- wcurl/_index.html
And add instructions to install manpage.
https://github.com/curl/wcurl/issues/21
> wcurl/_index.html: Use link to latest release to install it

- _changes.html
The previous estimate (1 Jan 1997) is most likely wrong. Kjell Ericson found an email from me to him dated January 17, 1997 in which I email him a copy of httpget 0.2. It seems reasonable to assume that I would have emailed him the latest version at the time, so therfore 0.3 cannot have been released until *after* January 17.
Hence, I move the estimated release date forward one month.
> changes: adjust release date for 0.3

- docs/_comparison-table.html
Ref: https://aria2.github.io/manual/en/html/aria2c.html#cmdoption-certificate
Reported-by: Vulpes Vulpes
Fixes #426
> comparison-table: add client cert for aria2c

- wcurl/_index.html
since it will be bundled in coming curl releases and the man page is no longer in nroff format in the git repo
> wcurl: update for new install instructions

- rc/_index.html
fixes for what I think are “typos” after browsing from https://mastodon.social/@bagder/114434508745355021. unbuilt and untested, sorry.
> Update rc’s _index.html for typos

- windows/_microsoft.html
Repaired broken link to Microsoft announcement, adding attributes `rel` and `target` to tag. Added new link to Microsoft Feedback Hub for reporting issues to Microsoft. Set additional link attributes for outside domains accordingly.
> windows: fix and add link and set attribute

- docs/_ssl-compared.html
* TLS 1.0 and TLS 1.1 have never been supported
* FIPS has been supported since [rustls-ffi 0.15.0](https://github.com/rustls/rustls-ffi/releases/tag/v0.15.0) w/ aws-lc-rs crypto
* Adds a link to the project page in the mentioned libraries
> docs: update SSL compared Rustls data

- _download.html
- order the tarball downloads by size (smallest first)
- use slightly larger text for the tarballs
> download: call it pgp, not gpg

- .github/dependabot.yml
- .github/scripts/requirements-docs.txt
- .github/workflows/spellcheck.yml
To avoid these extra layers when using `pyspelling`:
- a GitHub Action
- a docker container image
- Docker Hub
The cost is a slower install step. Benefits are 3x faster, parallel
spellcheck, being in sync with the same logic in curl/curl, and direct
pin and bump for the pip package. Mostly the latters, because this is
a rarely run CI job, and speed isn't critical.
pyspelling is configured to use aspell and aspell-en. These packages
are not seeing many updates anymore, and after this patch aspell is
bumped to its latest minor revision 0.60.8.1 (from 0.60.8):
https://sources.debian.org/src/aspell/
https://sources.debian.org/src/aspell-en/
> GHA: use `pyspelling` directly, setup yearly Dependabot updates
