curl/curl-www

- docs/_menu.html
I noticed some broken links when browsing the site. This should fix the ones I found.
> docs: fix broken links

- curl.css
Bug: https://twitter.com/RReverser/status/1410726567722905607
Fixes: #131
> dashboard: fix dark mode colors

- _download.html
Adding quay link for pulling curl image.
> Add quay link to pull/download curl image

- ca/update.sh
Co-authored-by: Frank Gevaerts
Fixes #267
> ca: fix .pem filenames in versioned .sha256 files

- .github/scripts/spellcheck.words
Fixes spellcheck issues on commits. :)
> spellcheck.words: Add TOCTOU as an allowed word

- _index.html
- Remove #if 0 text
- Add WS and WSS
- rename SSL to TLS
- add a few more device cateogories often using curl
- bump to twenty billion installs
- over 2900 contributors now
> index: refresh

- docs/_comparison-table.html
- HAPROXY protocol
- HTTP AWS Sigv4 Auth
- IPFS gateway
> docs/_comparison-table.html: compare three more features

- _web-editing.html
focus on edit and content, lead the build part to the README in the repo
> web-editing: overhaul

- mail/Makefile
- mail/_etiquette.html
As it changed format in the source repo
> mail/_etiquette: render from markdown now

- _web-editing.html
- dev/_roadmap.html
- dev/_source.html
Nothing terribly exciting here.
> Fix assorted typos

- libcurl/c/Makefile
- libcurl/c/_allfuncs.html
- libcurl/c/mkallfunc.pl
1. makes it up-to-date automatically
2. include the short description
3. make it a table to look a little easier on the eye
4. no more "deprecated" section in the bottom
> allfuncs: generate the list from source

- libcurl/c/Makefile
- libcurl/c/_curl_multi_socket_all.html
It previously shared page with curl_multi_socket
> libcurl/c/curl_multi_socket_all: new manpage

- snapshots/Makefile
- snapshots/_index.html
And reduce the amount of text on the page
Put the tarballs in the left column
> snapshots: include an updated time stamp

- wcurl/_index.html
> wcurl/_index.html: explain how to install it

- docs/CVE-2024-8096.md
> docs/CVE-2024-8096.md: spell check

- curl.css
> curl.css: adjust `code` background color in dark mode

- docs/CVE-2019-5443.md
To match the full desc as used in vuln.pm
> CVE-2019-5443.md: fix the CWE description

- docs/CVE-2024-11053.md
- docs/vuln.pm
This problem was introduced much later than previously thought, proven by bisects.
Researched-by: Yihang Zhou
> CVE-2024-11053.md: adjusted the introduced-in data

- docs/_companies.html
Reported-by: Marius Albrecht
Fixes #430
> companies: fix typo and quote symbol

- docs/_irc.html
> irc: add Matrix information

- rc/_index.html
- rc/mkindex.pl
Also separate each RC somewhat
Fixes https://github.com/curl/curl/issues/16776
> rc: link the commit for each rc

- _doctype.html
> Update `_doctype.html`: use HTML5 doctype

- libcurl/c/Makefile
- libcurl/c/_curl_easy_ssls_export.html
- libcurl/c/_curl_easy_ssls_import.html
Reported-by: Qriist on github
Fixes #458
> libcurl/c/curl_easy_ssls_*: new manpages

- curl.css
> curl.css: remove 'tailmenu'

- docs/_comparison-table.html
Fixes https://github.com/curl/curl-www/issues/479
> comparison-table: xh updates
